### ISSUE TITLE
unable to import plugin into composition

### ISSUE THREAD

**Issue by jgastonraoul** [McZonk/QCMyo#1]
Hi,

I'm working with Quartz Composer 4.6 on OS X 10.9.5.
I've installed QCMyo to the right place (I've tried both "/Library/Graphics/Quartz \Composer \Plug-ins" and "~/Library/Graphics/Quartz \Composer \Plug-ins"). I can see the plugin in my library, but when I try to move it to the editor, nothing happens.
Any idea on why this doesn't work ?

Regards,

Jeremie

**Comment by McZonk** [comment]
Any Console messages? When you can see a plug-in but you cannot instantiate it, it is a hint that the plug-in crashed. There should be a log in Console.app at least. Maybe that is helpful.

**Comment by jgastonraoul** [comment]
I'm sorry but I'm not very familiar with QC. I've tried to find a log window inside QC but I haven't.
How do you open Console.app ? It is just a separate application that connects to QC ?

**Comment by jonathanhammond** [comment]
Max is referring to the standard system console. Type ‘Console' into a spotlight search. Or goto Applications > Utilities

**Comment by jgastonraoul** [comment]
Thanks for your reply : I'll try that tonight and keep you informed.

**Comment by McZonk** [comment]
I updated the plug-in to be compatible with Myo firmware 1.15 and Connect Manager 0.8.0. https://github.com/McZonk/QCMyo/releases/tag/v1.1

Please check if this is fixing your bug. If not try to select the plug-in in the Library and open the sample to see if this is working.

**Comment by McZonk** [comment]
I hope the problem was solved.
