### ISSUE TITLE
Plugin not appearing in Library.

### ISSUE THREAD

**Issue by FuzzBeast** [McZonk/QCMyo#2]
I cannot seem to get this plugin to appear in Quartz Composer. I have tried both the release version and building from the master in Xcode, neither to any success. I have tried both in the correct folder (~/Graphics/Quartz Composer Plug-Ins). 
I'm fairly experienced with QC and am kind of thrown for a loop as to what to do to make this plugin appear. Does it maybe have something to do with the current version of the Myo firmware being 1.3.1448  and the SDK now being at 0.8.1, both of which are newer than the compatible listed on the release and main page? Otherwise, any ideas as to why I cannot get the plugin to appear in the library?

**Comment by McZonk** [comment]
I updated the plug-in to work with the latest Myo SDK. But I don't think that this will make a difference.
The plug-in is Yosemite (10.10) compatible only and it will only work when Quartz Composer is running in 64-bit mode.

**Comment by FuzzBeast** [comment]
So I finally got it to work, something was screwed up with the way my computer was interacting with some groups of plugins, anyway, I was wondering, is there a way to detect multiple Myo? I have 2 with a need for them to be able to communicate separately.

**Comment by McZonk** [comment]
Please add comments to https://github.com/McZonk/QCMyo/issues/3 for multiple Myos support.
